In [1]:
import numpy as np
import math
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2
import NormalizedFixed_Matrix as normMtx
import _fixedInt as fInt

In [2]:
def PlataformaVerificacion():
    
    import math
    
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    
    N = int(input('Numero de filas = Numero de columnas = ')) # Filas
    
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: ')) 

#    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)         #Genera las NMtx solicitadas y las concatena para
    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)

############### PARAMETROS DE CUANTIZACION ###########################

    ####### PARAMETRIZACION MANUAL ###################################
    
#    print('PARAMETRIZACION MANUAL DE LAS ENTRADAS :')

#    Input_Data_Type = int(input('Ingrese 'float' o 'fixed' segun el tipo de dato que desea en las entradas: '))
#    rango = int(input('Ingrese el rango de normalizacion: '))
#    NB = int(input('Ingrese número de bits totales: '))
#    NB_F = int(input('Ingrese número de bits fraccionales: '))
#    print("Indique si se utilizará redondeo(round) o truncamiento(trunc) y el modo de saturación(saturate/overflow)")
#    roundMode = input("roundMode >> ")
#    saturateMode = input("saturateMode >> ")

#    print('PARAMETRIZACION MANUAL DE LAS salidas :')

#    NB_OUT = int(input('Ingrese número de bits totales: '))


########### PARAMETRIZACION AUTOMATICA ###############################
    
    # PARAMETRIZACION AUTOMATICA DE LAS ENTRADAS
    
    Input_Data_Type = 'fixed'
    rango = 255
    NB = 8
    NB_F = 7
    roundMode = 'round'
    saturateMode = 'saturate'
    
    # PARAMETRIZACION AUTOMATICA DE LAS SALIDAS
    
#    NB_OUT = 10
#    NB_OUT_F = int(NB_OUT - 2 - math.ceil(math.log2(N))) 
    
    # CASO FULL RESOLUTION
    
    NB_OUT = NB * 2 + math.ceil(math.log2(N))
    NB_OUT_F = NB_F * 2
    
    
    print('NB_OUT :',NB_OUT)
    print('NB_OUT_F :',NB_OUT_F)
    
######################################################################
    
#    [premult_A,postmult_B] = normMtx.NormalizedFixedMatrix(rango, premult_A, postmult_B, NB, roundMode, saturateMode)
    
    [premult_A_stream,postmult_B_stream] = inputgen.InputGenerator(Input_Data_Type,rango, premult_A, postmult_B, NB, NB_F, roundMode, saturateMode)

    print('premult_A_stream:\n',premult_A_stream)
    print('postmult_B_stream:\n',postmult_B_stream)
    
#    countsysmult.CounterGenSysMult(premult_A_stream,postmult_B_stream)
    countsysmult2.CounterGenSysMult2(premult_A_stream,postmult_B_stream,rango,NB_OUT,NB_OUT_F)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas =  7

 Numero de multiplicaciones matriciales:  4


B_aux[m] en m = :  0

 [11. 12. 13. 14. 15. 16. 17.]
B_aux[m] en m = :  1

 [21. 22. 23. 24. 25. 26. 27.]
B_aux[m] en m = :  2

 [31. 32. 33. 34. 35. 36. 37.]
B_aux[m] en m = :  3

 [41. 42. 43. 44. 45. 46. 47.]
B_aux[m] en m = :  4

 [51. 52. 53. 54. 55. 56. 57.]
B_aux[m] en m = :  5

 [61. 62. 63. 64. 65. 66. 67.]
B_aux[m] en m = :  6

 [71. 72. 73. 74. 75. 76. 77.]
len(A_aux) 7
len(A_aux[0]) 7
A_aux 
 [[11. 12. 13. 14. 15. 16. 17.]
 [21. 22. 23. 24. 25. 26. 27.]
 [31. 32. 33. 34. 35. 36. 37.]
 [41. 42. 43. 44. 45. 46. 47.]
 [51. 52. 53. 54. 55. 56. 57.]
 [61. 62. 63. 64. 65. 66. 67.]
 [71. 72. 73. 74. 75. 76. 77.]]
len(B_aux) 7
len(B_aux[0]) 7
B_aux 
 [[77. 76. 75. 74. 73. 72. 71.]
 [67. 66. 65. 64. 63. 62. 61.]
 [57. 56. 55. 54. 53. 52. 51.]
 [47. 46. 45. 44. 43. 42. 41.]
 [37. 36. 35. 34. 33. 32. 31.]
 [27. 26. 25. 24. 23. 22. 21.]
 [17. 16. 15. 14. 13. 12. 11.]]
B_aux[m] en m = :  0

 [11. 12. 13. 14. 15. 16. 17.]
B_aux[m] en m = :  1

 [21. 22. 23. 24. 25. 26. 27.]
B_aux[m] en m